```{r}
library(tidyverse)
library(sf)
library(here)

# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

# filter to a state you are interested in
california <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "CA") 

# filter to a county you are interested in
san_bernardino <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("San Bernardino County"))

# find the average values for all variables within counties
california_counties <- aggregate(california, by = list(california$CNTY_NAME), FUN = mean)
```

P_CANCER
Percentile for Air toxics cancer risk

```{r}
install.packages("stars")
install.packages("tmap")
```

```{r}
library(sf)
library(stars)
library(tmap)
library(here)

tm_shape(san_bernardino) + 
  tm_polygons('LOWINCPCT',
              fill.legend = tm_legend(title = 'Proportion of Low Income Residents'),
              fill.scale = tm_scale(values = 'YlOrRd')
  ) +
  tm_title('Low Income Population in San Bernardino County') +
  tm_compass(position = c('top', 'right')) +
  tm_scalebar()
```

P_LIFEEXPPCT
Percentile for Low Life Expectancy

```{r}
tm_shape(san_bernardino) +
  tm_polygons('PTSDF',
              fill.legend = tm_legend(title = 'Hazard Waste Proximity (National Percentile Rank)'),
              fill.scale = tm_scale(values = 'YlOrRd')
  
  ) +
  tm_title('Hazard Waste Proximity in San Bernardino County') +
  tm_compass(position = c('top', 'right')) +
  tm_scalebar()
```